CREATE TABLE keys (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  key_type TEXT NOT NULL, -- 'ssh' or 'gpg'
  title TEXT NOT NULL,
  key_data TEXT NOT NULL,
  fingerprint TEXT NOT NULL UNIQUE,
  last_used_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
